# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gone < Formula
  desc "A fast, concurrent dead link detector for markdown files"
  homepage "https://github.com/leonardomso/gone"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.0/gone_0.1.0_darwin_amd64.tar.gz"
      sha256 "8208ced50d2dd458c53d9e0af04b65a35d542faf69248ece0d2d2f1337ccf052"

      def install
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.0/gone_0.1.0_darwin_arm64.tar.gz"
      sha256 "a3a802fd16cc24ea2092b50e3fe9aef5cae370fc5b09d38eb388d40747fe2d1d"

      def install
        bin.install "gone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.0/gone_0.1.0_linux_amd64.tar.gz"
      sha256 "de643500668547b3aa3b313ab6226533256513cd8f9eac910214e1d62d435a34"
      def install
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.0/gone_0.1.0_linux_arm64.tar.gz"
      sha256 "8af6ff443fdaf4bcc45789040aac56ee88c88abbd0b71a15c960be5873318715"
      def install
        bin.install "gone"
      end
    end
  end

  test do
    system "#{bin}/gone", "--help"
  end
end
