# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gone < Formula
  desc "A fast, concurrent dead link detector for markdown files"
  homepage "https://github.com/leonardomso/gone"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.5/gone_0.1.5_darwin_amd64.tar.gz"
      sha256 "4da0ce22adb03fefd37ec9d57e4e1a56a59265821681e27c2fb58079b18a432c"

      def install
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.5/gone_0.1.5_darwin_arm64.tar.gz"
      sha256 "39945c566b3350a4d3c0c907d53ef8b127f0df2ae70046132997bd31cef83c74"

      def install
        bin.install "gone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.5/gone_0.1.5_linux_amd64.tar.gz"
      sha256 "31f876f789782b4faae318e7684629633d3105050760f59852262824b48bcd41"
      def install
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.5/gone_0.1.5_linux_arm64.tar.gz"
      sha256 "74a1d842b6fa62ce612ad6893bc391712405282533fd8eb1e8fb1ea1bf85cf01"
      def install
        bin.install "gone"
      end
    end
  end

  test do
    system "#{bin}/gone", "--help"
  end
end
