# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gone < Formula
  desc "A fast, concurrent dead link detector for markdown files"
  homepage "https://github.com/leonardomso/gone"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.6/gone_0.1.6_darwin_amd64.tar.gz"
      sha256 "7da8c4fbaf62f9971dfe35c391e9755975f9b749238eb91a36f36ef522f7f212"

      define_method(:install) do
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.6/gone_0.1.6_darwin_arm64.tar.gz"
      sha256 "201ba8a19d5fa68d8f9639347bd0800d8831c2ed383ef942db4bf73086e3bdbf"

      define_method(:install) do
        bin.install "gone"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.6/gone_0.1.6_linux_amd64.tar.gz"
      sha256 "944934566ceb16102c4f982fcc87f4a2bbe2a689abc39bbfc3a3d5034f4a8063"
      define_method(:install) do
        bin.install "gone"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leonardomso/gone/releases/download/v0.1.6/gone_0.1.6_linux_arm64.tar.gz"
      sha256 "4b1d8b1728e12815e37fe79663430f77e21daec4c889dc5ef6f0f616e4c82522"
      define_method(:install) do
        bin.install "gone"
      end
    end
  end

  test do
    system "#{bin}/gone", "--help"
  end
end
